
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.VBox PassangerProps;

	private global::Gtk.Entry NamePassanger;

	private global::Gtk.Entry Telephone;

	private global::Gtk.Entry Email;

	private global::Gtk.VBox PassangerPropsTextView;

	private global::Gtk.TextView NameTextView;

	private global::Gtk.TextView TelephoneTextView;

	private global::Gtk.TextView EmailTextView;

	private global::Gtk.Button BookTicket;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PassangerProps = new global::Gtk.VBox();
		this.PassangerProps.Name = "PassangerProps";
		this.PassangerProps.Spacing = 10;
		// Container child PassangerProps.Gtk.Box+BoxChild
		this.NamePassanger = new global::Gtk.Entry();
		this.NamePassanger.CanFocus = true;
		this.NamePassanger.Name = "NamePassanger";
		this.NamePassanger.IsEditable = true;
		this.NamePassanger.InvisibleChar = '•';
		this.PassangerProps.Add(this.NamePassanger);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.PassangerProps[this.NamePassanger]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child PassangerProps.Gtk.Box+BoxChild
		this.Telephone = new global::Gtk.Entry();
		this.Telephone.CanFocus = true;
		this.Telephone.Name = "Telephone";
		this.Telephone.IsEditable = true;
		this.Telephone.InvisibleChar = '•';
		this.PassangerProps.Add(this.Telephone);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.PassangerProps[this.Telephone]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child PassangerProps.Gtk.Box+BoxChild
		this.Email = new global::Gtk.Entry();
		this.Email.CanFocus = true;
		this.Email.Name = "Email";
		this.Email.IsEditable = true;
		this.Email.InvisibleChar = '•';
		this.PassangerProps.Add(this.Email);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.PassangerProps[this.Email]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.fixed1.Add(this.PassangerProps);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.PassangerProps]));
		w4.X = 23;
		w4.Y = 23;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PassangerPropsTextView = new global::Gtk.VBox();
		this.PassangerPropsTextView.WidthRequest = 80;
		this.PassangerPropsTextView.HeightRequest = 100;
		this.PassangerPropsTextView.Name = "PassangerPropsTextView";
		this.PassangerPropsTextView.Spacing = 19;
		// Container child PassangerPropsTextView.Gtk.Box+BoxChild
		this.NameTextView = new global::Gtk.TextView();
		this.NameTextView.Buffer.Text = global::Mono.Unix.Catalog.GetString("Name");
		this.NameTextView.CanFocus = true;
		this.NameTextView.Name = "NameTextView";
		this.NameTextView.Editable = false;
		this.PassangerPropsTextView.Add(this.NameTextView);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.PassangerPropsTextView[this.NameTextView]));
		w5.Position = 0;
		// Container child PassangerPropsTextView.Gtk.Box+BoxChild
		this.TelephoneTextView = new global::Gtk.TextView();
		this.TelephoneTextView.Buffer.Text = global::Mono.Unix.Catalog.GetString("Telephone");
		this.TelephoneTextView.CanFocus = true;
		this.TelephoneTextView.Name = "TelephoneTextView";
		this.TelephoneTextView.Editable = false;
		this.PassangerPropsTextView.Add(this.TelephoneTextView);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.PassangerPropsTextView[this.TelephoneTextView]));
		w6.Position = 1;
		// Container child PassangerPropsTextView.Gtk.Box+BoxChild
		this.EmailTextView = new global::Gtk.TextView();
		this.EmailTextView.Buffer.Text = global::Mono.Unix.Catalog.GetString("Email");
		this.EmailTextView.CanFocus = true;
		this.EmailTextView.Name = "EmailTextView";
		this.PassangerPropsTextView.Add(this.EmailTextView);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.PassangerPropsTextView[this.EmailTextView]));
		w7.Position = 2;
		this.fixed1.Add(this.PassangerPropsTextView);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.PassangerPropsTextView]));
		w8.X = 223;
		w8.Y = 28;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BookTicket = new global::Gtk.Button();
		this.BookTicket.CanFocus = true;
		this.BookTicket.Name = "BookTicket";
		this.BookTicket.UseUnderline = true;
		this.BookTicket.Label = global::Mono.Unix.Catalog.GetString("Book Ticket");
		this.fixed1.Add(this.BookTicket);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.BookTicket]));
		w9.X = 149;
		w9.Y = 147;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 556;
		this.DefaultHeight = 470;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.BookTicket.Clicked += new global::System.EventHandler(this.OnRegestrationClicked);
	}
}
